apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lab
spec:
  selector:
    matchLabels:
      app: lab
      component: playground
      container: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: lab
        component: playground
        container: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
